//
//  Language.m
//  GoogleDictionary
//
//  Created by Yu Jianjun on 8/10/10.
//  Copyright 2010 Cybercom. All rights reserved.
//

#import "Language.h"
/*
extern NSString *const AUTO_DETECT = @"";
extern NSString *const AFRIKAANS = @"af",
extern NSString *const ALBANIAN("sq"),
extern NSString *const AMHARIC("am"),
extern NSString *const ARABIC("ar"),
extern NSString *const ARMENIAN("hy"),
extern NSString *const AZERBAIJANI("az"),
extern NSString *const BASQUE("eu"),
extern NSString *const BELARUSIAN("be"),
extern NSString *const BENGALI("bn"),
extern NSString *const BIHARI("bh"),
extern NSString *const BULGARIAN("bg"),
extern NSString *const BURMESE("my"),
extern NSString *const CATALAN("ca"),
extern NSString *const CHEROKEE("chr"),
extern NSString *const CHINESE("zh"),
extern NSString *const CHINESE_SIMPLIFIED("zh-CN"),
extern NSString *const CHINESE_TRADITIONAL("zh-TW"),
extern NSString *const CROATIAN("hr"),
extern NSString *const FRENCH("fr"),
extern NSString *const GALICIAN("gl"),
extern NSString *const GEORGIAN("ka"),
extern NSString *const GERMAN("de"),
extern NSString *const GREEK("el"),
extern NSString *const GUARANI("gn"),
extern NSString *const GUJARATI("gu"),
extern NSString *const HEBREW("iw"),
extern NSString *const HINDI("hi"),
extern NSString *const HUNGARIAN("hu"),
extern NSString *const ICELANDIC("is"),
extern NSString *const INDONESIAN("id"),
extern NSString *const INUKTITUT("iu"),
extern NSString *const IRISH("ga"),
extern NSString *const ITALIAN("it"),
extern NSString *const JAPANESE("ja"),
extern NSString *const KANNADA("kn"),
extern NSString *const KAZAKH("kk"),
extern NSString *const KHMER("km"),
extern NSString *const KOREAN("ko"),
extern NSString *const KURDISH("ku"),
extern NSString *const KYRGYZ("ky"),
extern NSString *const LAOTHIAN("lo"),
extern NSString *const LATVIAN("lv"),
extern NSString *const LITHUANIAN("lt"),
extern NSString *const MACEDONIAN("mk"),
extern NSString *const MALAY("ms"),
extern NSString *const MALAYALAM("ml"),
extern NSString *const MALTESE("mt"),
extern NSString *const MARATHI("mr"),
extern NSString *const MONGOLIAN("mn"),
extern NSString *const NEPALI("ne"),
extern NSString *const NORWEGIAN("no"),
extern NSString *const ORIYA("or"),
extern NSString *const PASHTO("ps"),
extern NSString *const PERSIAN("fa"),
extern NSString *const POLISH("pl"),
extern NSString *const PORTUGUESE("pt"),
extern NSString *const PUNJABI("pa"),
extern NSString *const ROMANIAN("ro"),
extern NSString *const RUSSIAN("ru"),
extern NSString *const SANSKRIT("sa"),
extern NSString *const SERBIAN("sr"),
extern NSString *const SINDHI("sd"),
extern NSString *const SINHALESE("si"),
extern NSString *const SLOVAK("sk"),
extern NSString *const SLOVENIAN("sl"),
extern NSString *const SPANISH("es"),
extern NSString *const SWAHILI("sw"),
extern NSString *const SWEDISH("sv"),
extern NSString *const TAJIK("tg"),
extern NSString *const TAMIL("ta"),
extern NSString *const TAGALOG("tl"),
extern NSString *const TELUGU("te"),
extern NSString *const THAI("th"),
extern NSString *const TIBETAN("bo"),
extern NSString *const TURKISH("tr"),
extern NSString *const UKRANIAN("uk"),
extern NSString *const URDU("ur"),
extern NSString *const UZBEK("uz"),
extern NSString *const UIGHUR("ug"),
extern NSString *const VIETNAMESE("vi"),
extern NSString *const WELSH("cy"),
extern NSString *const YIDDISH("yi");
*/
@implementation Language

@end
